### ISSUE TITLE
Allow Eyegrade to edit session settings before the grading process is started

### ISSUE THREAD

**Issue by rgnodev** [jfisteus/eyegrade#100]
It would be nice to have an 'edit' option in the 'session' menu, so you can change session settings before you start to grade your exams. This way, you would be allowed to correct any error in the session settings (e.g. question answers, students list, question weights, etc) with no need to create the whole session again.

**Comment by jfisteus** [comment]
Issue #103 supersedes this issue. Progress can be checked there.
