### ISSUE TITLE
Add option to save exam.eye file with the new session wizard

### ISSUE THREAD

**Issue by rgnodev** [jfisteus/eyegrade#102]
With the upcoming release, an improved new-session wizard will allow the user to create an exam configuration file from the GUI. However, the new wizard currently doesn't allow you to save this file in order to use it later with a different session. An option to do it should be added.

**Comment by jfisteus** [comment]
I find it a useful suggestion. I've implemented it in the session-wizard branch. The feature will be available at the Tools menu in the next release.
