### ISSUE TITLE
Accept button disabled in the student id dialog

### ISSUE THREAD

**Issue by jfisteus** [jfisteus/eyegrade#108]
I've seen that in a particular environment (Gnome 3, probably) sometimes the *Accept* button remains disabled after the selected student changes. Selecting that student again in the combo box enables the button.

**Comment by jfisteus** [comment]
I've seen the error again on Windows with version 0.6.2. When the user clicks on a student with the mouse the Accept button remains disabled. It works fine when the user selects the student with the keyboard.

**Comment by rgnodev** [comment]
I'm performing some tests, as a user, of eyegrade 0.6.3+ (current development version), and the issue seems to be back (or, at least, to remain unfixed in this branch).

**Comment by jfisteus** [comment]
The issue needs to be investigated again.

**Comment by jfisteus** [comment]
Development is still affected. Reopening the issue one more time!!!

**Comment by jfisteus** [comment]
False alarm. The issue that made me reopen the bug happened in eyegrade 0.6.3, but the fix to the bug was applied in 0.6.4.
