### ISSUE TITLE
The pyinstaller package for Linux does not work on some Ubuntu systems

### ISSUE THREAD

**Issue by jfisteus** [jfisteus/eyegrade#125]
It is unable to import cv2 and finishes with the error message:

```
Cannot import cv2. You need to install OpenCV 2.4 and its Python bindings.
```

**Comment by cnt5bs** [comment]
Hi jesus. After updating the OpenCV installation to version 3, I noticed that "eyegrade" works on version 2.4 only (on my Linux Mint). Should anyone need to reinstall to 2.4, I followed the script developed by https://www.samontab.com/web/2014/06/installing-opencv-2-4-9-in-ubuntu-14-04-lts. Thank you.

**Comment by jfisteus** [comment]
Thanks for letting me know about the link to install OpenCV 2.4. Starting next week I plan to dedicate some time to try to adapt eyegrade to work not only on OpenCV 2.4 but also on versions 3.2, 3.3 and 3.4. You can follow the status of the task by subscribing to issue #117.

**Comment by jfisteus** [comment]
The development branch at GitHub should now support OpenCV 2.4, 3.2, 3.3 and 3.4. Details at issue #117. In addition, it uses PyQt5 instead of PyQt4. I'll try to release it as a stable version sometime in the next weeks.

**Comment by jfisteus** [comment]
A machine that previously failed with this issue does no longer fail when building the binary with the Python 3.5 + OpenCV 3.4.1 + PyInstaller 3.3.1 (the future eyegrade 0.8 release).

It was built on a Debian stretch machine. I'll test with a binary built on older machines (probably Ubuntu 16.04 LTS).

**Comment by jfisteus** [comment]
The linux binaries for Eyegrade 0.8 should no longer suffer from this.
