### ISSUE TITLE
Customized OMR Sheet

### ISSUE THREAD

**Issue by ginterez** [jfisteus/eyegrade#141]
Will this work with customized OMR Sheet?

![57649181_2481928055173444_8169883942887882752_n](https://user-images.githubusercontent.com/45252867/57119283-7f067980-6d9b-11e9-8203-e8148fcad084.jpg)

**Comment by jfisteus** [comment]
No, it won't work. Eyegrade only detects answer sheets with the structure you see in it's documentation and examples.

**Comment by ginterez** [comment]
Will it work with 22 questions in it?
