### ISSUE TITLE
How can I make session without answer key?

### ISSUE THREAD

**Issue by ginterez** [jfisteus/eyegrade#142]
I am currently working with teacher evaluation rating form here in our university. And I'm trying to work with your eyegrade. And since there's no fixed answer to an evaluation unlike exams I am having hard time configuring your program. Is it possible to make eyegrade session without an answer key (model answer)???

**Comment by jfisteus** [comment]
The survey mode worked some time ago, but I didn't have the occasion to integrate it in the current user interface. If you can wait one or two weeks I can try to dedicate some time to make it work again.

**Comment by ginterez** [comment]
Thank you sir! It is much appreciated. By the way, I also included and cited eyegrade in my documentation. And you sir, will also be in the acknowledgement, thank you sir.

**Comment by ginterez** [comment]
is this available?

**Comment by jfisteus** [comment]
I prepared the internals last week, but I couldn't get time yet to prepare the user interface so that you can configure the survey mode through the "New session" dialog. I hope I'll be able to do that next week.

**Comment by jfisteus** [comment]
Even if the GUI is not prepared as I mentioned, If you want to try out the system, update your git repository (`git pull` from the `development` branch), create a new session with the following session file:

https://www.eyegrade.org/examples/20190516-surveys/survey.eye

Then, scan the following survey:

https://www.eyegrade.org/examples/20190516-surveys/survey.pdf

You can create your own survey PDF as long as the answer table has a similar geometry. Beware in that case that the answer table cannot be too wide or too tall. Keep the proportions of the example to be on the safe side. 

Let me know if anything fails.

**Comment by jfisteus** [comment]
The new session wizard can now create a session for surveys:

1. Create a new session (Menu *Session/New session*)

2. Select the session directory and choose *Configure a survey manually*

![wizard-survey-1](https://user-images.githubusercontent.com/912913/58562001-ae889480-8228-11e9-963f-08a4f7a4ca7f.png)

3. Configure the number of choices per questions and the number of questions per answer box (left to right). In the following example, 6 choices per questions and two answer boxes with 11 questions each:

![wizard-survey-2](https://user-images.githubusercontent.com/912913/58562125-e55eaa80-8228-11e9-960e-3f91de8c8e5f.png)

4. If you don't need to link scanned sheets to users, just skip the next page:

![wizard-survey-3](https://user-images.githubusercontent.com/912913/58562168-00c9b580-8229-11e9-88d6-bf3a18cca751.png)

5. Leave also the next page with its default values:

![wizard-survey-4](https://user-images.githubusercontent.com/912913/58562282-3c647f80-8229-11e9-841c-439beddffd09.png)

6. Try it with the following survey answer sheet:

https://www.eyegrade.org/examples/20190516-surveys/survey.pdf
